# Generated by Django 2.2.25 on 2021-12-10 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sells', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='time_created',
        ),
        migrations.AddField(
            model_name='review',
            name='time_last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
