# Generated by Django 2.2.25 on 2021-12-10 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20211210_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='time_created',
        ),
        migrations.AddField(
            model_name='product',
            name='time_last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
